description: boiling-blizzard checkpoint inference config for anemoi-inference.

checkpoint: /leonardo_work/AIFAC_5C0_154/enordhag/bris_checkpoints/boiling-blizzard_r6_3kit_ifs.ckpt
runner: default

# Override on the CLI as needed, for example:
#   anemoi-inference run boiling-blizzard.yaml date=2024-01-01T00:00:00 lead_time=120h
date: 2023-12-01T00:00:00
lead_time: 9528h

device: cuda
verbosity: 1
report_error: true
write_initial_state: true
output_frequency: 6h

input:
  dataset:
    dataset: /leonardo_work/DestE_340_25/ai-ml/datasets/aifs-od-an-oper-0001-mars-n320-2016-2025-6h-v1-for-single-v2.zarr
    select:
      - 10u
      - 10v
      - 2d
      - 2t
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - hcc
      - insolation
      - lcc
      - lsm
      - mcc
      - msl
      - q_100
      - q_1000
      - q_150
      - q_200
      - q_250
      - q_300
      - q_400
      - q_50
      - q_500
      - q_700
      - q_850
      - q_925
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude
      - skt
      - sp
      - ssrd
      - strd
      - t_100
      - t_1000
      - t_150
      - t_200
      - t_250
      - t_300
      - t_400
      - t_50
      - t_500
      - t_700
      - t_850
      - t_925
      - tcc
      - tcw
      - tp
      - u_100
      - u_1000
      - u_150
      - u_200
      - u_250
      - u_300
      - u_400
      - u_50
      - u_500
      - u_700
      - u_850
      - u_925
      - v_100
      - v_1000
      - v_150
      - v_200
      - v_250
      - v_300
      - v_400
      - v_50
      - v_500
      - v_700
      - v_850
      - v_925
      - w_100
      - w_1000
      - w_150
      - w_200
      - w_250
      - w_300
      - w_400
      - w_50
      - w_500
      - w_700
      - w_850
      - w_925
      - z
      - z_100
      - z_1000
      - z_150
      - z_200
      - z_250
      - z_300
      - z_400
      - z_50
      - z_500
      - z_700
      - z_850
      - z_925

output:
  netcdf:
    path: ./netcdf/boiling-blizzard-__RUN_ID__.nc
